# Generated by Django 3.0.4 on 2020-04-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='foodrecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('foodname', models.CharField(max_length=100)),
                ('fid', models.IntegerField()),
                ('occuation', models.TextField()),
                ('prepared', models.IntegerField()),
                ('wasted', models.IntegerField()),
            ],
        ),
    ]
