# Generated by Django 3.0.4 on 2020-04-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecords',
            name='date',
            field=models.DateField(),
        ),
    ]
