# Generated by Django 3.0.4 on 2020-04-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200402_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('foodname', models.CharField(max_length=100)),
                ('fid', models.IntegerField()),
                ('description', models.TextField()),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
