# Generated by Django 3.0.4 on 2020-04-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_foodratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecords',
            name='day',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
